title: "The ROLE Collective"
author: "Blog Author"
description: "The ROLE Collective Website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
markdown: GFM

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "ROLESymposium.md"} 
  - {title: "Call for ROLE Symposium Submissions", url: "https://uiowa.qualtrics.com/jfe/form/SV_8ABXmEpwD3IDmS2"}
  - {title: "Join Us", url: "https://docs.google.com/forms/d/e/1FAIpQLSdLTW5-pOeImube-nGj2AieVYGosdUfb5BbzA9ov8xQjAAMIw/viewform?usp=sf_link"}
 # - {file: "CoreStatement.md"} 
 # - {title: "Contribute", url: "https://forms.gle/8v8Pc1eAqN8d7BzF8"}
  - {file: "resources.md"} 


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:rolecollective@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/rolecollective/"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
